### ISSUE TITLE
Rename project & namespace.

### ISSUE THREAD

**Issue by DHCPCD9** [VolcanicArts/osu-request#12]
Hello, I would ask to rename project. Due to conventions name of project (and namespace) looks bad.

I think you should rename to `OsuRequest` or something like that.

**Comment by DHCPCD9** [comment]
Only namespace.

**Comment by VolcanicArts** [comment]
I've stopped working on this project for the time being as I've got university to focus on, however, I've got plans for a Version 2 that will bring some new features and graphical changes as well as the namespace change as requested. The reason I've made it a completely new version is I've learnt a lot about the framework since starting this project and it's beneficial for me to start over instead of trying to fix the old code.
